/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import EntityWrapper from "../hoc/EntityWrapper";
import GameEntityType from "../types/GameEntityType";

type GLTFResult = any & GLTF & {
  nodes: {
    Building_Mesh: THREE.Mesh
    Building_Mesh_1: THREE.Mesh
    Building_Mesh_2: THREE.Mesh
    Building_Mesh_3: THREE.Mesh
    Building_Mesh_4: THREE.Mesh
    Building_Mesh_5: THREE.Mesh
    Building_Mesh_6: THREE.Mesh
    Building_Mesh_7: THREE.Mesh
  }
  materials: {
    ['material.002']: THREE.MeshStandardMaterial
    ['material_42.002']: THREE.MeshStandardMaterial
    ['material_47.002']: THREE.MeshStandardMaterial
    ['material.003']: THREE.MeshStandardMaterial
    ['material_50.002']: THREE.MeshStandardMaterial
    ['material_57.002']: THREE.MeshStandardMaterial
    ['material.004']: THREE.MeshStandardMaterial
    ['material.005']: THREE.MeshStandardMaterial
  }
}

export default function BuildingHouse1 (props: GameEntityType) {
  const { nodes, materials } = useGLTF('/assets/building_house_1.glb') as GLTFResult
  return (
    <EntityWrapper {...props}>
      <group scale={[0.0009,0.0009, 0.00105]} rotation={[0,Math.PI,Math.PI]} position={[-0.3,0,0.22]}>
        <mesh geometry={nodes.Building_Mesh.geometry} material={materials['material.002']} />
        <mesh geometry={nodes.Building_Mesh_1.geometry} material={materials['material_42.002']} />
        <mesh geometry={nodes.Building_Mesh_2.geometry} material={materials['material_47.002']} />
        <mesh geometry={nodes.Building_Mesh_3.geometry} material={materials['material.003']} />
        <mesh geometry={nodes.Building_Mesh_4.geometry} material={materials['material_50.002']} />
        <mesh geometry={nodes.Building_Mesh_5.geometry} material={materials['material_57.002']} />
        <mesh geometry={nodes.Building_Mesh_6.geometry} material={materials['material.004']} />
        <mesh geometry={nodes.Building_Mesh_7.geometry} material={materials['material.005']} />
      </group>
    </EntityWrapper>
  )
}

useGLTF.preload('/assets/building_house_1.glb')
