/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import {Plane, useGLTF} from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import TileWrapper from "../hoc/TileWrapper";
import GameEntityType from "../types/GameEntityType";

type GLTFResult = any & GLTF & {
  nodes: {
    Mesh001: THREE.Mesh
    Mesh002: THREE.Mesh
    Mesh003: THREE.Mesh
    Mesh004: THREE.Mesh
    Mesh005: THREE.Mesh
    Mesh006: THREE.Mesh
    Mesh007: THREE.Mesh
    Mesh008: THREE.Mesh
    Mesh009: THREE.Mesh
    Mesh010: THREE.Mesh
    Mesh011: THREE.Mesh
    Mesh012: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh013: THREE.Mesh
  }
  materials: {
    ['.1_3.002']: THREE.MeshStandardMaterial
    ['material_3.002']: THREE.MeshStandardMaterial
    ['material_4.002']: THREE.MeshStandardMaterial
    ['material_6.002']: THREE.MeshStandardMaterial
    ['material_7.002']: THREE.MeshStandardMaterial
    ['material_35.003']: THREE.MeshStandardMaterial
    ['material_36.002']: THREE.MeshStandardMaterial
    ['.14_0.002']: THREE.MeshStandardMaterial
    ['.8_0.002']: THREE.MeshStandardMaterial
    ['material_46.002']: THREE.MeshStandardMaterial
    ['material_48.002']: THREE.MeshStandardMaterial
    ['.13_0.002']: THREE.MeshStandardMaterial
    ['1_1__13.002']: THREE.MeshStandardMaterial
    ['.2_2.002']: THREE.MeshStandardMaterial
  }
}

export default function GasStation(props: GameEntityType) {
  const { nodes, materials } = useGLTF('/assets/gas_station.glb') as GLTFResult
  return (
    <TileWrapper  {...props}>
      <group scale={[0.0009, 0.001, 0.001]} position={[0.5,0,0.5]} rotation-y={Math.PI}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['.1_3.002']} />
        <mesh geometry={nodes.Mesh002.geometry} material={materials['material_3.002']} />
        <mesh geometry={nodes.Mesh003.geometry} material={materials['material_4.002']} />
        <mesh geometry={nodes.Mesh004.geometry} material={materials['material_6.002']} />
        <mesh geometry={nodes.Mesh005.geometry} material={materials['material_7.002']} />
        <mesh geometry={nodes.Mesh006.geometry} material={materials['material_35.003']} />
        <mesh geometry={nodes.Mesh007.geometry} material={materials['material_36.002']} />
        <mesh geometry={nodes.Mesh008.geometry} material={materials['.14_0.002']} />
        <mesh geometry={nodes.Mesh009.geometry} material={materials['.8_0.002']} rotation={[0, 0, -0.23]} />
        <mesh geometry={nodes.Mesh010.geometry} material={materials['material_46.002']} />
        <mesh geometry={nodes.Mesh011.geometry} material={materials['material_48.002']} />
        <mesh geometry={nodes.Mesh012.geometry} material={materials['.13_0.002']} rotation={[0, 0, -0.23]} />
        <mesh geometry={nodes.Mesh.geometry} material={materials['1_1__13.002']} />
        <mesh geometry={nodes.Mesh013.geometry} material={materials['.2_2.002']} />
      </group>
      <Plane
        args={[2,2]}
        rotation-x={-Math.PI/2}
        material-color={"gray"}
        position={[0.5,0,0.5]}
      />
    </TileWrapper>
  )
}

useGLTF.preload('/assets/gas_station.glb')
