/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import {Plane, useGLTF} from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import GameEntityType from "../types/GameEntityType";
import EntityWrapper from "../hoc/EntityWrapper";

type GLTFResult = any & GLTF & {
  nodes: {
    Store_mesh: THREE.Mesh
    Store_mesh_1: THREE.Mesh
    Store_mesh_2: THREE.Mesh
    Store_mesh_3: THREE.Mesh
    Store_mesh_4: THREE.Mesh
    Store_mesh_5: THREE.Mesh
    Store_mesh_6: THREE.Mesh
    Store_mesh_7: THREE.Mesh
  }
  materials: {
    ['material_44.002']: THREE.MeshStandardMaterial
    ['material_35.004']: THREE.MeshStandardMaterial
    ['material_39.002']: THREE.MeshStandardMaterial
    ['material.012']: THREE.MeshStandardMaterial
    ['material_43.002']: THREE.MeshStandardMaterial
    ['material_46.003']: THREE.MeshStandardMaterial
    ['material_56.002']: THREE.MeshStandardMaterial
    ['material.013']: THREE.MeshStandardMaterial
  }
}

export default function Store(props: GameEntityType) {
  const { nodes, materials } = useGLTF('/assets/store.glb') as GLTFResult
  return (
    <EntityWrapper {...props}>
      <group position={[-0.2, 0, 0.2]} scale={0.001} rotation-y={Math.PI}>
        <mesh geometry={nodes.Store_mesh.geometry} material={materials['material_44.002']} />
        <mesh geometry={nodes.Store_mesh_1.geometry} material={materials['material_35.004']} />
        <mesh geometry={nodes.Store_mesh_2.geometry} material={materials['material_39.002']} />
        <mesh geometry={nodes.Store_mesh_3.geometry} material={materials['material.012']} />
        <mesh geometry={nodes.Store_mesh_4.geometry} material={materials['material_43.002']} />
        <mesh geometry={nodes.Store_mesh_5.geometry} material={materials['material_46.003']} />
        <mesh geometry={nodes.Store_mesh_6.geometry} material={materials['material_56.002']} />
        <mesh geometry={nodes.Store_mesh_7.geometry} material={materials['material.013']} />
      </group>
      <Plane
        args={[2,3]}
        rotation-x={-Math.PI/2}
        material-color={"gray"}
        position={[0,0,0.2]}
      />
    </EntityWrapper>
  )
}

useGLTF.preload('/assets/store.glb')
