/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, {useEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Ground: THREE.Mesh
    Water: THREE.Mesh
  }
  materials: {
    material_3: THREE.MeshStandardMaterial
    material_60: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  //@ts-ignore
  const { scene } = useGLTF('/assets/terain.glb', true) as GLTFResult


  return (
    <primitive object={scene}></primitive>
  )
}

useGLTF.preload('/Terrain.glb')
